export const ROUTERS_NAME = {
	main: '/main',
	login: '/login',
	users: '/users',
	settings: '/settings',
	manageFrontOffice: '/manage-front-office',
	courses: '/courses',
	classroom: '/classroom',
	translation: '/translation',
	statistics: '/statistics',
	accounts: '/accounts',
	communities: '/communities',
	geography: '/geography',
	roles: '/roles',
	channels: '/channels',
	thematics: '/thematics',
	arborescence: '/arborescence',
	contentLocation: '/content-location',
	action: '/action',
};
