export const QUERY_KEYS_ACCOUNTS = {
	GET_LIST_FILTER_OPTIONS: 'GET_LIST_FILTER_OPTIONS',
	GET_LIST_BRANDS: 'GET_LIST_BRANDS',
};
export const QUERY_KEY_REGIONS = {
	GET_LIST_REGIONS: 'GET_LIST_REGIONS',
};
export const QUERY_KEY_COMMUNITIES = {
	GET_LIST_COMMUNITIES: 'GET_LIST_COMMUNITIES',
};
export const QUERY_KEYS_USERS = {
	GET_LIST_USERS: 'GET_LIST_USERS',
};
